INSERT INTO USER (USERNAME, PASSWORD) VALUES ('anh', '$2a$10$bC0b1VAKGdzKA5/etBhbCO2eHc69pzxOPBNj7k/CpCHgy5hyLFR5S');
INSERT INTO USER (USERNAME, PASSWORD) VALUES ('pham', '$2a$10$zj8bIuJXnNwAlbskQbJd7.YMZbQq0Yoj1Ir.U6nRH5MePcyKSRewW');

INSERT INTO AUTH_USER (USERNAME, AUTH_GROUP) VALUES('anh', 'USER');
INSERT INTO AUTH_USER (USERNAME, AUTH_GROUP) VALUES('anh', 'ADMIN');
INSERT INTO AUTH_USER (USERNAME, AUTH_GROUP) VALUES('pham', 'USER');